### ISSUE TITLE
Small Nitpicking 

### ISSUE THREAD

**Issue by ThomasThelen** [hillarykoch/lemon_practice#1]
Looks fun!

https://github.com/hillarykoch/lemon_practice/blob/master/main.cpp#L48
`.size()` returns type `size_type` which is really an unsigned int. I think it's common to do something like `for(auto i = 0; i < all_paths.size(); i++){`.
Not a big deal, but you can find more on it [here](https://stackoverflow.com/questions/131803/unsigned-int-vs-size-t).
`auto` will type `i` as an `unsigned int`, without you having to type it all out.

`std::endl` can be really slow in a loop because it flushes the output buffer-especially if it's going to be in a library.
https://github.com/hillarykoch/lemon_practice/blob/master/main.cpp#L49
https://stackoverflow.com/questions/213907/c-stdendl-vs-n

**Comment by hillarykoch** [comment]
Appreciate it, thanks! The std::endl was just for my debugging and has all been removed, but I will incorporate changes regarding your remarks on .size().
